INSERT INTO public.ien_applicant_status(status) VALUES ('IEN HMBC Process');
INSERT INTO public.ien_applicant_status(status) VALUES ('IEN Licensing/Registration');
INSERT INTO public.ien_applicant_status(status) VALUES ('IEN Recruitment (once licensed)');
INSERT INTO public.ien_applicant_status(status) VALUES ('BC PNP (once job offer obtained and if immigration required)');
INSERT INTO public.ien_applicant_status(status) VALUES ('Final Milestone');

-- IEN HMBC Process
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HMBC - Registered for HMBC services', (SELECT id FROM public.ien_applicant_status WHERE status='IEN HMBC Process'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HMBC - Profile Complete', (SELECT id FROM public.ien_applicant_status WHERE status='IEN HMBC Process'));

-- IEN Licensing/Registration
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Applied to NNAS', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Documents Submitted (NNAS Application in Review)', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Received NNAS Report', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Applied to BCCNM', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Completed English Language Requirement*', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Referred to NCAS*', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Completed Computer-Based Assessment (CBA)*', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Completed Oral Assessment (OA) and Simulation Lab Assessment (SLA)*', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Completed NCAS*', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Referred to Additional Education*', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Completed Additional Education*', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Referred to NCLEX*', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Eligible for Provisional Licensure*', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - NCLEX - Written', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - NCLEX - Passed ', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - BCCNM Licensed - Full License', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Licensing/Registration'));


-- IEN Recruitment (once licensed)
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HMBC - Applicant ready for job search', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Acknowledgement/Referral Reviewed', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Pre-Screen Process', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Not Interested', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - No Position Available', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Candidate Withdrawn', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - CV Forwarded (to Hiring Manager)', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Interview', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Reference Check', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Job Offer sent', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Job offer accepted', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Hired', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));
-- INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Referred to BC PNP (if immigration required, see below)*', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)'));

DELETE FROM public.ien_applicant_status WHERE parent_id IN (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)');
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Prescreen completed', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)' limit 1));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Interview completed', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)' limit 1));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('References completed', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)' limit 1));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Offered position', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)' limit 1));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate withdrew', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)' limit 1));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate was unresponsive', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)' limit 1));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate was not selected ', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)' limit 1));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate accepted the job offer', (SELECT id FROM public.ien_applicant_status WHERE status='IEN Recruitment (once licensed)' limit 1));


-- BC PNP (once job offer obtained and if immigration required)
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HMBC - First Steps Document Sent', (SELECT id FROM public.ien_applicant_status WHERE status='BC PNP (once job offer obtained and if immigration required)'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Documents sent to HMBC', (SELECT id FROM public.ien_applicant_status WHERE status='BC PNP (once job offer obtained and if immigration required)'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Application Submitted to BC PNP', (SELECT id FROM public.ien_applicant_status WHERE status='BC PNP (once job offer obtained and if immigration required)'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Confirmation of Nomination Received', (SELECT id FROM public.ien_applicant_status WHERE status='BC PNP (once job offer obtained and if immigration required)'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HMBC - Second Steps Sent', (SELECT id FROM public.ien_applicant_status WHERE status='BC PNP (once job offer obtained and if immigration required)'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Work Permit Application Submitted *', (SELECT id FROM public.ien_applicant_status WHERE status='BC PNP (once job offer obtained and if immigration required)'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Work Permit Approval Letter Received *', (SELECT id FROM public.ien_applicant_status WHERE status='BC PNP (once job offer obtained and if immigration required)'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Arrival in Canada - Work Permit Received', (SELECT id FROM public.ien_applicant_status WHERE status='BC PNP (once job offer obtained and if immigration required)'));
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('Candidate - Permanent Residency', (SELECT id FROM public.ien_applicant_status WHERE status='BC PNP (once job offer obtained and if immigration required)'));

-- Final Milestone
INSERT INTO public.ien_applicant_status(status, parent_id) VALUES ('HA - Candidate started job', (SELECT id FROM public.ien_applicant_status WHERE status='Final Milestone'));



-- HA/PCN Comm

INSERT INTO public.ien_ha_pcn(title) VALUES ('FHA');
INSERT INTO public.ien_ha_pcn(title) VALUES ('FNHA');
INSERT INTO public.ien_ha_pcn(title) VALUES ('IHA');
INSERT INTO public.ien_ha_pcn(title) VALUES ('NHA');
INSERT INTO public.ien_ha_pcn(title) VALUES ('PHC');
INSERT INTO public.ien_ha_pcn(title) VALUES ('PHSA');
INSERT INTO public.ien_ha_pcn(title) VALUES ('VCHA');
INSERT INTO public.ien_ha_pcn(title) VALUES ('VIHA');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Fraser Northwest');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Vancouver');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Richmond');
INSERT INTO public.ien_ha_pcn(title) VALUES ('South Okanagan Similkameen');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Burnaby');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Saanich Peninsula');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Western Communities');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Kootenay Boundary');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Ridge Meadows');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Central Okanagan');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Chilliwack');
INSERT INTO public.ien_ha_pcn(title) VALUES ('East Kootenay');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Oceanside');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Comox');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Cowichan Valley');
INSERT INTO public.ien_ha_pcn(title) VALUES ('North Shore');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Nanaimo');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Central Interior Rural');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Mission');
INSERT INTO public.ien_ha_pcn(title) VALUES ('North Peace');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Northern Interior Rural');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Pacific Northwest');
INSERT INTO public.ien_ha_pcn(title) VALUES ('White Rock/South Surrey');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Prince George');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Campbell River');
INSERT INTO public.ien_ha_pcn(title) VALUES ('Sea to Sky (Squamish)');
INSERT INTO public.ien_ha_pcn(title) VALUES ('North Okanagan');
INSERT INTO public.ien_ha_pcn(title) VALUES ('GovBC');


-- Assigned To

INSERT INTO public.ien_users(name) VALUES ('Chadi');
INSERT INTO public.ien_users(name) VALUES ('Nicole');


-- Education list

INSERT INTO public.ien_education(title) VALUES ('Diploma/Certificate of Nursing');
INSERT INTO public.ien_education(title) VALUES ('Associate Degree of Nursing');
INSERT INTO public.ien_education(title) VALUES ('Bachelor of Nursing or Bachelor of Science in Nursing');
INSERT INTO public.ien_education(title) VALUES ('Master of Nursing');
INSERT INTO public.ien_education(title) VALUES ('Master of Nursing - Nurse Practitioner');
INSERT INTO public.ien_education(title) VALUES ('PhD');
INSERT INTO public.ien_education(title) VALUES ('Combined Diploma/Degree in Midwifery & Nursing');



-- Job titles / Sub Specialty

INSERT INTO public.ien_job_titles(title) VALUES ('Aboriginal Health Nursing');
INSERT INTO public.ien_job_titles(title) VALUES ('Administration');
INSERT INTO public.ien_job_titles(title) VALUES ('Advanced Practice');
INSERT INTO public.ien_job_titles(title) VALUES ('Ambulatory Care');
INSERT INTO public.ien_job_titles(title) VALUES ('Cardiology - CCU/Telemetry');
INSERT INTO public.ien_job_titles(title) VALUES ('Chronic Disease/Diabetes');
INSERT INTO public.ien_job_titles(title) VALUES ('Clinical Educator');
INSERT INTO public.ien_job_titles(title) VALUES ('Clinical Coordinator');
INSERT INTO public.ien_job_titles(title) VALUES ('Clinical Nurse Leader');
INSERT INTO public.ien_job_titles(title) VALUES ('Communicable Disease Control');
INSERT INTO public.ien_job_titles(title) VALUES ('Community Health');
INSERT INTO public.ien_job_titles(title) VALUES ('Critical Care/ICU');
INSERT INTO public.ien_job_titles(title) VALUES ('Critical Care/Transport');
INSERT INTO public.ien_job_titles(title) VALUES ('Education');
INSERT INTO public.ien_job_titles(title) VALUES ('Emergency Room/Trauma');
INSERT INTO public.ien_job_titles(title) VALUES ('Family Practice');
INSERT INTO public.ien_job_titles(title) VALUES ('Geriatrics/Gerontology');
INSERT INTO public.ien_job_titles(title) VALUES ('Home Care');
INSERT INTO public.ien_job_titles(title) VALUES ('Infection Control');
INSERT INTO public.ien_job_titles(title) VALUES ('Management');
INSERT INTO public.ien_job_titles(title) VALUES ('Maternity (Antepartum & Postpartum)');
INSERT INTO public.ien_job_titles(title) VALUES ('Maternity (Labour & Delivery)');
INSERT INTO public.ien_job_titles(title) VALUES ('Medicine/Surgery');
INSERT INTO public.ien_job_titles(title) VALUES ('Midwifery');
INSERT INTO public.ien_job_titles(title) VALUES ('Neonatal Intensive Care');
INSERT INTO public.ien_job_titles(title) VALUES ('Neurology');
INSERT INTO public.ien_job_titles(title) VALUES ('New Graduate');
INSERT INTO public.ien_job_titles(title) VALUES ('Nurse Executive');
INSERT INTO public.ien_job_titles(title) VALUES ('Occupational Health');
INSERT INTO public.ien_job_titles(title) VALUES ('Oncology');
INSERT INTO public.ien_job_titles(title) VALUES ('Operating Room (Adult)');
INSERT INTO public.ien_job_titles(title) VALUES ('Operating Room (Pediatric)');
INSERT INTO public.ien_job_titles(title) VALUES ('Outreach');
INSERT INTO public.ien_job_titles(title) VALUES ('Palliative Care');
INSERT INTO public.ien_job_titles(title) VALUES ('Pediatrics');
INSERT INTO public.ien_job_titles(title) VALUES ('Post Anesthetic Recovery');
INSERT INTO public.ien_job_titles(title) VALUES ('Primary Care Clinic');
INSERT INTO public.ien_job_titles(title) VALUES ('Psychiatry/Mental Health');
INSERT INTO public.ien_job_titles(title) VALUES ('Public Health');
INSERT INTO public.ien_job_titles(title) VALUES ('Rehabilitation');
INSERT INTO public.ien_job_titles(title) VALUES ('Rehabilitation/Spinal Unit');
INSERT INTO public.ien_job_titles(title) VALUES ('Renal Dialysis');
INSERT INTO public.ien_job_titles(title) VALUES ('Research');
INSERT INTO public.ien_job_titles(title) VALUES ('Still in School');
INSERT INTO public.ien_job_titles(title) VALUES ('Transitional Care Nurse');
INSERT INTO public.ien_job_titles(title) VALUES ('Wound Care');


-- Job Locations
INSERT INTO public.ien_job_locations(title) VALUES ('100 Mile House');
INSERT INTO public.ien_job_locations(title) VALUES ('Abbotsford');
INSERT INTO public.ien_job_locations(title) VALUES ('Agassiz and Harrison');
INSERT INTO public.ien_job_locations(title) VALUES ('Ahousat');
INSERT INTO public.ien_job_locations(title) VALUES ('Aldergrove');
INSERT INTO public.ien_job_locations(title) VALUES ('Alert Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Alexandria');
INSERT INTO public.ien_job_locations(title) VALUES ('Alexis Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Alice Arm - Kitsault');
INSERT INTO public.ien_job_locations(title) VALUES ('Anahim Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Anmore');
INSERT INTO public.ien_job_locations(title) VALUES ('Argenta');
INSERT INTO public.ien_job_locations(title) VALUES ('Armstrong');
INSERT INTO public.ien_job_locations(title) VALUES ('Ashcroft');
INSERT INTO public.ien_job_locations(title) VALUES ('Atlin');
INSERT INTO public.ien_job_locations(title) VALUES ('Avola');
INSERT INTO public.ien_job_locations(title) VALUES ('Balfour');
INSERT INTO public.ien_job_locations(title) VALUES ('Bamfield');
INSERT INTO public.ien_job_locations(title) VALUES ('Barkerville');
INSERT INTO public.ien_job_locations(title) VALUES ('Barnston Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Barriere');
INSERT INTO public.ien_job_locations(title) VALUES ('Beaverdell');
INSERT INTO public.ien_job_locations(title) VALUES ('Belcarra');
INSERT INTO public.ien_job_locations(title) VALUES ('Bell II');
INSERT INTO public.ien_job_locations(title) VALUES ('Bella Bella');
INSERT INTO public.ien_job_locations(title) VALUES ('Bella Coola');
INSERT INTO public.ien_job_locations(title) VALUES ('Big White');
INSERT INTO public.ien_job_locations(title) VALUES ('Blind Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Blue River');
INSERT INTO public.ien_job_locations(title) VALUES ('Blueberry River');
INSERT INTO public.ien_job_locations(title) VALUES ('Boston Bar');
INSERT INTO public.ien_job_locations(title) VALUES ('Boswell');
INSERT INTO public.ien_job_locations(title) VALUES ('Bowen Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Bralorne');
INSERT INTO public.ien_job_locations(title) VALUES ('Bridesville');
INSERT INTO public.ien_job_locations(title) VALUES ('Bridge Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Britannia Beach');
INSERT INTO public.ien_job_locations(title) VALUES ('Broman Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Burnaby');
INSERT INTO public.ien_job_locations(title) VALUES ('Burns Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Cache Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Campbell River');
INSERT INTO public.ien_job_locations(title) VALUES ('Canal Flats');
INSERT INTO public.ien_job_locations(title) VALUES ('Canim Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Cassiar');
INSERT INTO public.ien_job_locations(title) VALUES ('Cassidy');
INSERT INTO public.ien_job_locations(title) VALUES ('Castlegar');
INSERT INTO public.ien_job_locations(title) VALUES ('Cawston');
INSERT INTO public.ien_job_locations(title) VALUES ('Cedar');
INSERT INTO public.ien_job_locations(title) VALUES ('Central Saanich');
INSERT INTO public.ien_job_locations(title) VALUES ('Chase');
INSERT INTO public.ien_job_locations(title) VALUES ('Chemainus');
INSERT INTO public.ien_job_locations(title) VALUES ('Cherryville');
INSERT INTO public.ien_job_locations(title) VALUES ('Cheslatta');
INSERT INTO public.ien_job_locations(title) VALUES ('Chetwynd');
INSERT INTO public.ien_job_locations(title) VALUES ('Chilanko Forks');
INSERT INTO public.ien_job_locations(title) VALUES ('Chilliwack');
INSERT INTO public.ien_job_locations(title) VALUES ('Christina Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Clearwater');
INSERT INTO public.ien_job_locations(title) VALUES ('Clinton');
INSERT INTO public.ien_job_locations(title) VALUES ('Cloverdale');
INSERT INTO public.ien_job_locations(title) VALUES ('Coalmont');
INSERT INTO public.ien_job_locations(title) VALUES ('Cobble Hill');
INSERT INTO public.ien_job_locations(title) VALUES ('Coldstream');
INSERT INTO public.ien_job_locations(title) VALUES ('Colwood');
INSERT INTO public.ien_job_locations(title) VALUES ('Comox');
INSERT INTO public.ien_job_locations(title) VALUES ('Coombs');
INSERT INTO public.ien_job_locations(title) VALUES ('Coquitlam');
INSERT INTO public.ien_job_locations(title) VALUES ('Cortes Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Courtenay');
INSERT INTO public.ien_job_locations(title) VALUES ('Cowichan Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Craigellachie');
INSERT INTO public.ien_job_locations(title) VALUES ('Cranbrook');
INSERT INTO public.ien_job_locations(title) VALUES ('Crawford Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Crescent Valley');
INSERT INTO public.ien_job_locations(title) VALUES ('Creston');
INSERT INTO public.ien_job_locations(title) VALUES ('Crofton');
INSERT INTO public.ien_job_locations(title) VALUES ('Cultus Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Cumberland');
INSERT INTO public.ien_job_locations(title) VALUES ('D''Arcy');
INSERT INTO public.ien_job_locations(title) VALUES ('Dawson Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Dease Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Deep Cove');
INSERT INTO public.ien_job_locations(title) VALUES ('Deer Park');
INSERT INTO public.ien_job_locations(title) VALUES ('Delta');
INSERT INTO public.ien_job_locations(title) VALUES ('Denman Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Deroche');
INSERT INTO public.ien_job_locations(title) VALUES ('Dog Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Doig River');
INSERT INTO public.ien_job_locations(title) VALUES ('Duncan');
INSERT INTO public.ien_job_locations(title) VALUES ('Edgewood');
INSERT INTO public.ien_job_locations(title) VALUES ('Egmont');
INSERT INTO public.ien_job_locations(title) VALUES ('Elkford');
INSERT INTO public.ien_job_locations(title) VALUES ('Endako');
INSERT INTO public.ien_job_locations(title) VALUES ('Enderby');
INSERT INTO public.ien_job_locations(title) VALUES ('Esquimalt');
INSERT INTO public.ien_job_locations(title) VALUES ('Falkland');
INSERT INTO public.ien_job_locations(title) VALUES ('Fanny Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Fauquier');
INSERT INTO public.ien_job_locations(title) VALUES ('Fernie');
INSERT INTO public.ien_job_locations(title) VALUES ('Field');
INSERT INTO public.ien_job_locations(title) VALUES ('Fort Babine');
INSERT INTO public.ien_job_locations(title) VALUES ('Fort Fraser');
INSERT INTO public.ien_job_locations(title) VALUES ('Fort Langley');
INSERT INTO public.ien_job_locations(title) VALUES ('Fort Nelson');
INSERT INTO public.ien_job_locations(title) VALUES ('Fort St. James');
INSERT INTO public.ien_job_locations(title) VALUES ('Fort St. John');
INSERT INTO public.ien_job_locations(title) VALUES ('Fort Ware');
INSERT INTO public.ien_job_locations(title) VALUES ('Francois Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Fraser Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Fruitvale');
INSERT INTO public.ien_job_locations(title) VALUES ('Gabriola Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Galiano Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Gambier Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Gibsons');
INSERT INTO public.ien_job_locations(title) VALUES ('Gilford Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Glade');
INSERT INTO public.ien_job_locations(title) VALUES ('Gold Bridge');
INSERT INTO public.ien_job_locations(title) VALUES ('Gold River');
INSERT INTO public.ien_job_locations(title) VALUES ('Golden');
INSERT INTO public.ien_job_locations(title) VALUES ('Grand Forks');
INSERT INTO public.ien_job_locations(title) VALUES ('Granisle');
INSERT INTO public.ien_job_locations(title) VALUES ('Grasmere');
INSERT INTO public.ien_job_locations(title) VALUES ('Grassy Plains');
INSERT INTO public.ien_job_locations(title) VALUES ('Greenville');
INSERT INTO public.ien_job_locations(title) VALUES ('Greenwood');
INSERT INTO public.ien_job_locations(title) VALUES ('Halfmoon Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Halfway River');
INSERT INTO public.ien_job_locations(title) VALUES ('Hanceville');
INSERT INTO public.ien_job_locations(title) VALUES ('Harrison Hot Springs');
INSERT INTO public.ien_job_locations(title) VALUES ('Harrop-Procter');
INSERT INTO public.ien_job_locations(title) VALUES ('Hartley Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Hazelton');
INSERT INTO public.ien_job_locations(title) VALUES ('Hedley');
INSERT INTO public.ien_job_locations(title) VALUES ('Highlands');
INSERT INTO public.ien_job_locations(title) VALUES ('Hills');
INSERT INTO public.ien_job_locations(title) VALUES ('Holberg');
INSERT INTO public.ien_job_locations(title) VALUES ('Hope');
INSERT INTO public.ien_job_locations(title) VALUES ('Hornby Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Horsefly');
INSERT INTO public.ien_job_locations(title) VALUES ('Horseshoe Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Hot Springs Cove');
INSERT INTO public.ien_job_locations(title) VALUES ('Houston');
INSERT INTO public.ien_job_locations(title) VALUES ('Howser');
INSERT INTO public.ien_job_locations(title) VALUES ('Hudson''s Hope');
INSERT INTO public.ien_job_locations(title) VALUES ('Invermere');
INSERT INTO public.ien_job_locations(title) VALUES ('Iskut');
INSERT INTO public.ien_job_locations(title) VALUES ('Jade City');
INSERT INTO public.ien_job_locations(title) VALUES ('Jaffray');
INSERT INTO public.ien_job_locations(title) VALUES ('Johnsons Landing');
INSERT INTO public.ien_job_locations(title) VALUES ('Jordan River');
INSERT INTO public.ien_job_locations(title) VALUES ('Kaleden');
INSERT INTO public.ien_job_locations(title) VALUES ('Kamloops');
INSERT INTO public.ien_job_locations(title) VALUES ('Kaslo');
INSERT INTO public.ien_job_locations(title) VALUES ('Keats Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Kelowna');
INSERT INTO public.ien_job_locations(title) VALUES ('Kent-Agassiz');
INSERT INTO public.ien_job_locations(title) VALUES ('Keremeos');
INSERT INTO public.ien_job_locations(title) VALUES ('Kimberley');
INSERT INTO public.ien_job_locations(title) VALUES ('Kincolith');
INSERT INTO public.ien_job_locations(title) VALUES ('Kingcome');
INSERT INTO public.ien_job_locations(title) VALUES ('Kitimat');
INSERT INTO public.ien_job_locations(title) VALUES ('Kitkatla');
INSERT INTO public.ien_job_locations(title) VALUES ('Kitsault');
INSERT INTO public.ien_job_locations(title) VALUES ('Kitwancool');
INSERT INTO public.ien_job_locations(title) VALUES ('Kitwanga');
INSERT INTO public.ien_job_locations(title) VALUES ('Kleena Kleene');
INSERT INTO public.ien_job_locations(title) VALUES ('Klemtu');
INSERT INTO public.ien_job_locations(title) VALUES ('Kootenay Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Kwadacha Fort Ware');
INSERT INTO public.ien_job_locations(title) VALUES ('Kyuquot');
INSERT INTO public.ien_job_locations(title) VALUES ('Ladner');
INSERT INTO public.ien_job_locations(title) VALUES ('Ladysmith');
INSERT INTO public.ien_job_locations(title) VALUES ('Lake Babine');
INSERT INTO public.ien_job_locations(title) VALUES ('Lake Country');
INSERT INTO public.ien_job_locations(title) VALUES ('Lake Cowichan');
INSERT INTO public.ien_job_locations(title) VALUES ('Langara Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Langford');
INSERT INTO public.ien_job_locations(title) VALUES ('Langley');
INSERT INTO public.ien_job_locations(title) VALUES ('Langley Township');
INSERT INTO public.ien_job_locations(title) VALUES ('Lantzville');
INSERT INTO public.ien_job_locations(title) VALUES ('Lasqueti Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Lavington');
INSERT INTO public.ien_job_locations(title) VALUES ('Liard River');
INSERT INTO public.ien_job_locations(title) VALUES ('Likely');
INSERT INTO public.ien_job_locations(title) VALUES ('Lillooet');
INSERT INTO public.ien_job_locations(title) VALUES ('Lions Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Little Fort');
INSERT INTO public.ien_job_locations(title) VALUES ('Logan Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Lone Butte');
INSERT INTO public.ien_job_locations(title) VALUES ('Lower Post');
INSERT INTO public.ien_job_locations(title) VALUES ('Lumby');
INSERT INTO public.ien_job_locations(title) VALUES ('Lund');
INSERT INTO public.ien_job_locations(title) VALUES ('Lytton');
INSERT INTO public.ien_job_locations(title) VALUES ('Mackenzie');
INSERT INTO public.ien_job_locations(title) VALUES ('Madeira Park');
INSERT INTO public.ien_job_locations(title) VALUES ('Malakwa');
INSERT INTO public.ien_job_locations(title) VALUES ('Maple Ridge');
INSERT INTO public.ien_job_locations(title) VALUES ('Masset');
INSERT INTO public.ien_job_locations(title) VALUES ('Mayne Island');
INSERT INTO public.ien_job_locations(title) VALUES ('McBride');
INSERT INTO public.ien_job_locations(title) VALUES ('McLeese Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('McLeod Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Meadow Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Merritt');
INSERT INTO public.ien_job_locations(title) VALUES ('Mesachie Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Metchosin');
INSERT INTO public.ien_job_locations(title) VALUES ('Metlakatla');
INSERT INTO public.ien_job_locations(title) VALUES ('Meziadin Junction');
INSERT INTO public.ien_job_locations(title) VALUES ('Mica Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Midway');
INSERT INTO public.ien_job_locations(title) VALUES ('Mill Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Miocene');
INSERT INTO public.ien_job_locations(title) VALUES ('Mission');
INSERT INTO public.ien_job_locations(title) VALUES ('Moberly Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Montrose');
INSERT INTO public.ien_job_locations(title) VALUES ('Moricetown');
INSERT INTO public.ien_job_locations(title) VALUES ('Mount Currie');
INSERT INTO public.ien_job_locations(title) VALUES ('Moyie');
INSERT INTO public.ien_job_locations(title) VALUES ('Muncho Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Nadleh');
INSERT INTO public.ien_job_locations(title) VALUES ('Nakusp');
INSERT INTO public.ien_job_locations(title) VALUES ('Nanaimo');
INSERT INTO public.ien_job_locations(title) VALUES ('Naramata');
INSERT INTO public.ien_job_locations(title) VALUES ('Nass Valley');
INSERT INTO public.ien_job_locations(title) VALUES ('Nazko');
INSERT INTO public.ien_job_locations(title) VALUES ('Needles');
INSERT INTO public.ien_job_locations(title) VALUES ('Nelson');
INSERT INTO public.ien_job_locations(title) VALUES ('Nemaiah Valley');
INSERT INTO public.ien_job_locations(title) VALUES ('New Aiyansh');
INSERT INTO public.ien_job_locations(title) VALUES ('New Denver');
INSERT INTO public.ien_job_locations(title) VALUES ('New Westminster');
INSERT INTO public.ien_job_locations(title) VALUES ('Nitinat');
INSERT INTO public.ien_job_locations(title) VALUES ('North Bend');
INSERT INTO public.ien_job_locations(title) VALUES ('North Cowichan');
INSERT INTO public.ien_job_locations(title) VALUES ('North Saanich');
INSERT INTO public.ien_job_locations(title) VALUES ('North Vancouver');
INSERT INTO public.ien_job_locations(title) VALUES ('North Vancouver District');
INSERT INTO public.ien_job_locations(title) VALUES ('Oak Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Ocean Falls');
INSERT INTO public.ien_job_locations(title) VALUES ('Okanagan Falls');
INSERT INTO public.ien_job_locations(title) VALUES ('Oliver');
INSERT INTO public.ien_job_locations(title) VALUES ('Osoyoos');
INSERT INTO public.ien_job_locations(title) VALUES ('Oyster River');
INSERT INTO public.ien_job_locations(title) VALUES ('Parksville');
INSERT INTO public.ien_job_locations(title) VALUES ('Pavillion');
INSERT INTO public.ien_job_locations(title) VALUES ('Peachland');
INSERT INTO public.ien_job_locations(title) VALUES ('Pemberton');
INSERT INTO public.ien_job_locations(title) VALUES ('Pender Harbour');
INSERT INTO public.ien_job_locations(title) VALUES ('Pender Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Penelakut Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Penticton');
INSERT INTO public.ien_job_locations(title) VALUES ('Pink Mountain');
INSERT INTO public.ien_job_locations(title) VALUES ('Pitt Meadows');
INSERT INTO public.ien_job_locations(title) VALUES ('Popkum');
INSERT INTO public.ien_job_locations(title) VALUES ('Port Alberni');
INSERT INTO public.ien_job_locations(title) VALUES ('Port Alice');
INSERT INTO public.ien_job_locations(title) VALUES ('Port Clements');
INSERT INTO public.ien_job_locations(title) VALUES ('Port Coquitlam');
INSERT INTO public.ien_job_locations(title) VALUES ('Port Edward');
INSERT INTO public.ien_job_locations(title) VALUES ('Port Hardy');
INSERT INTO public.ien_job_locations(title) VALUES ('Port McNeill');
INSERT INTO public.ien_job_locations(title) VALUES ('Port Moody');
INSERT INTO public.ien_job_locations(title) VALUES ('Port Renfrew');
INSERT INTO public.ien_job_locations(title) VALUES ('Port Simpson');
INSERT INTO public.ien_job_locations(title) VALUES ('Pouce Coupe');
INSERT INTO public.ien_job_locations(title) VALUES ('Powell River');
INSERT INTO public.ien_job_locations(title) VALUES ('Prince George');
INSERT INTO public.ien_job_locations(title) VALUES ('Prince Rupert');
INSERT INTO public.ien_job_locations(title) VALUES ('Princeton');
INSERT INTO public.ien_job_locations(title) VALUES ('Prophet River');
INSERT INTO public.ien_job_locations(title) VALUES ('Quadra Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Qualicum Beach');
INSERT INTO public.ien_job_locations(title) VALUES ('Quatsino');
INSERT INTO public.ien_job_locations(title) VALUES ('Queen Charlotte');
INSERT INTO public.ien_job_locations(title) VALUES ('Quesnel');
INSERT INTO public.ien_job_locations(title) VALUES ('Radium Hot Springs');
INSERT INTO public.ien_job_locations(title) VALUES ('Redsone Reserve');
INSERT INTO public.ien_job_locations(title) VALUES ('Revelstoke');
INSERT INTO public.ien_job_locations(title) VALUES ('Richmond');
INSERT INTO public.ien_job_locations(title) VALUES ('Riondel');
INSERT INTO public.ien_job_locations(title) VALUES ('Riske Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Rivers Inlet');
INSERT INTO public.ien_job_locations(title) VALUES ('Roberts Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Rock Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Rosedale');
INSERT INTO public.ien_job_locations(title) VALUES ('Rossland');
INSERT INTO public.ien_job_locations(title) VALUES ('Rosswood');
INSERT INTO public.ien_job_locations(title) VALUES ('Royston');
INSERT INTO public.ien_job_locations(title) VALUES ('Saanich');
INSERT INTO public.ien_job_locations(title) VALUES ('Saanichton');
INSERT INTO public.ien_job_locations(title) VALUES ('Salmo');
INSERT INTO public.ien_job_locations(title) VALUES ('Salmon Arm');
INSERT INTO public.ien_job_locations(title) VALUES ('Salt Spring Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Samahquam');
INSERT INTO public.ien_job_locations(title) VALUES ('Sandon');
INSERT INTO public.ien_job_locations(title) VALUES ('Sandspit');
INSERT INTO public.ien_job_locations(title) VALUES ('Saturna Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Savary Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Savona');
INSERT INTO public.ien_job_locations(title) VALUES ('Sayward');
INSERT INTO public.ien_job_locations(title) VALUES ('Scotch Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Sechelt');
INSERT INTO public.ien_job_locations(title) VALUES ('Seton Portage');
INSERT INTO public.ien_job_locations(title) VALUES ('Shawnigan Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Sicamous');
INSERT INTO public.ien_job_locations(title) VALUES ('Sidney');
INSERT INTO public.ien_job_locations(title) VALUES ('Silverton');
INSERT INTO public.ien_job_locations(title) VALUES ('Sirdar');
INSERT INTO public.ien_job_locations(title) VALUES ('Skatin');
INSERT INTO public.ien_job_locations(title) VALUES ('Skidegate');
INSERT INTO public.ien_job_locations(title) VALUES ('Slocan Park');
INSERT INTO public.ien_job_locations(title) VALUES ('Smithers');
INSERT INTO public.ien_job_locations(title) VALUES ('Sointula');
INSERT INTO public.ien_job_locations(title) VALUES ('Sooke');
INSERT INTO public.ien_job_locations(title) VALUES ('Sorrento');
INSERT INTO public.ien_job_locations(title) VALUES ('Spallumcheen');
INSERT INTO public.ien_job_locations(title) VALUES ('Sparwood');
INSERT INTO public.ien_job_locations(title) VALUES ('Spences Bridge');
INSERT INTO public.ien_job_locations(title) VALUES ('Squamish');
INSERT INTO public.ien_job_locations(title) VALUES ('Stewart');
INSERT INTO public.ien_job_locations(title) VALUES ('Summerland');
INSERT INTO public.ien_job_locations(title) VALUES ('Sun Peaks');
INSERT INTO public.ien_job_locations(title) VALUES ('Surrey');
INSERT INTO public.ien_job_locations(title) VALUES ('Tahsis');
INSERT INTO public.ien_job_locations(title) VALUES ('Takla Landing');
INSERT INTO public.ien_job_locations(title) VALUES ('Tatla Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Tatlayoko Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Taylor');
INSERT INTO public.ien_job_locations(title) VALUES ('Telegraph Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Telkwa');
INSERT INTO public.ien_job_locations(title) VALUES ('Terrace');
INSERT INTO public.ien_job_locations(title) VALUES ('Tête Jaune Cache');
INSERT INTO public.ien_job_locations(title) VALUES ('Texada Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Thetis Island');
INSERT INTO public.ien_job_locations(title) VALUES ('Tipella');
INSERT INTO public.ien_job_locations(title) VALUES ('Tlell');
INSERT INTO public.ien_job_locations(title) VALUES ('Tofino');
INSERT INTO public.ien_job_locations(title) VALUES ('Topley');
INSERT INTO public.ien_job_locations(title) VALUES ('Trail');
INSERT INTO public.ien_job_locations(title) VALUES ('Tranquille');
INSERT INTO public.ien_job_locations(title) VALUES ('Trout Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Tsawwassen');
INSERT INTO public.ien_job_locations(title) VALUES ('Tsay Keh Dene');
INSERT INTO public.ien_job_locations(title) VALUES ('Tulameen');
INSERT INTO public.ien_job_locations(title) VALUES ('Tumbler Ridge');
INSERT INTO public.ien_job_locations(title) VALUES ('Ucluelet');
INSERT INTO public.ien_job_locations(title) VALUES ('Union Bay');
INSERT INTO public.ien_job_locations(title) VALUES ('Usk');
INSERT INTO public.ien_job_locations(title) VALUES ('Valemount');
INSERT INTO public.ien_job_locations(title) VALUES ('Vancouver');
INSERT INTO public.ien_job_locations(title) VALUES ('Vanderhoof');
INSERT INTO public.ien_job_locations(title) VALUES ('Vaseux Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Vavenby');
INSERT INTO public.ien_job_locations(title) VALUES ('Vernon');
INSERT INTO public.ien_job_locations(title) VALUES ('Victoria');
INSERT INTO public.ien_job_locations(title) VALUES ('View Royal');
INSERT INTO public.ien_job_locations(title) VALUES ('Wardner');
INSERT INTO public.ien_job_locations(title) VALUES ('Warfield');
INSERT INTO public.ien_job_locations(title) VALUES ('Wasa');
INSERT INTO public.ien_job_locations(title) VALUES ('Wells');
INSERT INTO public.ien_job_locations(title) VALUES ('West Kelowna');
INSERT INTO public.ien_job_locations(title) VALUES ('West Vancouver');
INSERT INTO public.ien_job_locations(title) VALUES ('Westbank');
INSERT INTO public.ien_job_locations(title) VALUES ('Westbridge');
INSERT INTO public.ien_job_locations(title) VALUES ('Whistler');
INSERT INTO public.ien_job_locations(title) VALUES ('White Rock');
INSERT INTO public.ien_job_locations(title) VALUES ('Williams Lake');
INSERT INTO public.ien_job_locations(title) VALUES ('Wilson Creek');
INSERT INTO public.ien_job_locations(title) VALUES ('Windermere');
INSERT INTO public.ien_job_locations(title) VALUES ('Winlaw');
INSERT INTO public.ien_job_locations(title) VALUES ('Winter Harbour');
INSERT INTO public.ien_job_locations(title) VALUES ('Woodfibre');
INSERT INTO public.ien_job_locations(title) VALUES ('Woss');
INSERT INTO public.ien_job_locations(title) VALUES ('Yahk');
INSERT INTO public.ien_job_locations(title) VALUES ('Yale');
INSERT INTO public.ien_job_locations(title) VALUES ('Ymir');
INSERT INTO public.ien_job_locations(title) VALUES ('Zeballos');

