export const REPORT_FOUR_STEPS = [
  'Applied to NNAS',
  'Applied to BCCNM',
  'Completed English Language Requirement',
  'Referred to NCAS',
  'Completed NCAS',
  'Completed Additional Education',
  'NCLEX – Written',
  'NCLEX – Passed',
  'BCCNM Full Licence LPN',
  'BCCNM Full Licence RN',
  'BCCNM Provisional Licence RN',
  'Referred to Registration Exam',
  'Registered as an HCA',
  'Registration Journey Complete',
  'Withdrew from IEN program',
  'Applicant Ready for Job Search',
  'Applicant Referred to FNHA',
  'Applicant Referred to FHA',
  'Applicant Referred to IHA',
  'Applicant Referred to NHA',
  'Applicant Referred to PHC',
  'Applicant Referred to PHSA',
  'Applicant Referred to VCHA',
  'Applicant Referred to VIHA',
  'Granted full licensure',
  'Granted provisional licensure',
];
