import { STATUS } from '@ien/common';

export type DurationTableEntry = MilestoneDurationTableEntry<number>;
export type MilestoneTableEntry = MilestoneDurationTableEntry<Date>;

/**
 * milestone table entry for report 9 and 10
 */
export type MilestoneDurationTableEntry<T> = {
  id: string;

  registration_date?: Date;

  ha?: string;

  [STATUS.APPLIED_TO_NNAS]?: T;

  [STATUS.SUBMITTED_DOCUMENTS]?: T;

  [STATUS.RECEIVED_NNAS_REPORT]?: T;

  [STATUS.COMPLETED_LANGUAGE_REQUIREMENT]?: T;

  [STATUS.APPLIED_TO_BCCNM]?: T;

  [STATUS.REFERRED_TO_NCAS]?: T;

  [STATUS.COMPLETED_CBA]?: T;

  [STATUS.COMPLETED_SLA]?: T;

  [STATUS.COMPLETED_NCAS]?: T;

  [STATUS.REFERRED_TO_ADDITIONAL_EDUCTION]?: T;

  [STATUS.COMPLETED_ADDITIONAL_EDUCATION]?: T;

  [STATUS.REFERRED_TO_REGISTRATION_EXAM]?: T;

  [STATUS.NCLEX_WRITTEN]?: T;

  [STATUS.NCLEX_PASSED]?: T;

  [STATUS.REX_PN_WRITTEN]?: T;

  [STATUS.REX_PN_PASSED]?: T;

  [STATUS.BCCNM_PROVISIONAL_LICENSE_LPN]?: T;

  [STATUS.BCCNM_PROVISIONAL_LICENSE_RN]?: T;

  [STATUS.BCCNM_FULL_LICENCE_LPN]?: T;

  [STATUS.BCCNM_FULL_LICENSE_RN]?: T;

  [STATUS.REGISTERED_AS_AN_HCA]?: T;

  [STATUS.REGISTRATION_JOURNEY_COMPLETED]?: T;

  [STATUS.WITHDREW_FROM_PROGRAM]?: T;

  [STATUS.READY_FOR_JOB_SEARCH]?: T;

  [STATUS.REFERRED_TO_FHA]?: T;

  [STATUS.REFERRED_TO_FNHA]?: T;

  [STATUS.REFERRED_TO_IHA]?: T;

  [STATUS.REFERRED_TO_NHA]?: T;

  [STATUS.REFERRED_TO_PHC]?: T;

  [STATUS.REFERRED_TO_PHSA]?: T;

  [STATUS.REFERRED_TO_VCHA]?: T;

  [STATUS.REFERRED_TO_VIHA]?: T;

  [STATUS.REFERRAL_ACKNOWLEDGED]?: T;

  [STATUS.PRE_SCREEN_PASSED]?: T;

  [STATUS.PRE_SCREEN_NOT_PASSED]?: T;

  [STATUS.INTERVIEW_PASSED]?: T;

  [STATUS.INTERVIEW_NOT_PASSED]?: T;

  [STATUS.REFERENCE_CHECK_PASSED]?: T;

  [STATUS.REFERENCE_CHECK_NOT_PASSED]?: T;

  [STATUS.JOB_OFFER_ACCEPTED]?: T;

  [STATUS.JOB_OFFER_NOT_ACCEPTED]?: T;

  [STATUS.WITHDREW_FROM_COMPETITION]?: T;

  [STATUS.HA_NOT_INTERESTED]?: T;

  [STATUS.JOB_COMPETITION_CANCELLED]?: T;

  [STATUS.NO_POSITION_AVAILABLE]?: T;

  [STATUS.SENT_EMPLOYER_DOCUMENTS_TO_HMBC]?: T;

  [STATUS.SENT_FIRST_STEPS_DOCUMENT]?: T;

  [STATUS.SUBMITTED_BC_PNP_APPLICATION]?: T;

  [STATUS.RECEIVED_CONFIRMATION_OF_NOMINATION]?: T;

  [STATUS.SENT_SECOND_STEPS_DOCUMENT]?: T;

  [STATUS.SUBMITTED_WORK_PERMIT_APPLICATION]?: T;

  [STATUS.RECEIVED_WORK_PERMIT_APPROVAL_LETTER]?: T;

  [STATUS.RECEIVED_WORK_PERMIT]?: T;

  [STATUS.SUBMITTED_PR_APPLICATION]?: T;

  [STATUS.RECEIVED_PR]?: T;
};
