// numeric values are just placeholders for now

export const professionOptionsArray = [
  { value: 'nurse-practitioner', label: 'Nurse Practitioner' },
  { value: 'mlt', label: 'MLT' },
  { value: 'mrt', label: 'MRT' },
  { value: 'midwife', label: 'Midwife' },
  { value: 'nurse', label: 'Nurse' },
  { value: 'occupational-therapist', label: 'Occupational Therapist' },
  { value: 'physiotherapist', label: 'Physiotherapist' },
  { value: 'pharmacist', label: 'Pharmacist' },
  { value: 'sonographer', label: 'Sonographer' },
];

export const specialityOptionsArray = [
  { value: 'chronic-disease', label: 'Chronic Disease' },
  { value: 'diabetes', label: 'Diabetes' },
  { value: '1', label: 'Aboriginal Health Nursing' },
  { value: '11', label: 'Administration' },
  { value: '111', label: 'Advanced Practice' },
  { value: '1111', label: 'Ambulatory Care' },
  { value: '2', label: 'Cardiology - CCU/Telemetry' },
  { value: '3', label: 'Chronic Disease/Diabetes' },
  { value: '4', label: 'Clinical Educator' },
  { value: '5', label: 'Clinical Coordinator' },
  { value: '6', label: 'Clinical Nurse Leader' },
  { value: '7', label: 'Communicable Disease Control' },
  { value: '8', label: 'Community Health' },
  { value: '9', label: 'Critical Care/ICU' },
  { value: '0', label: 'Critical Care/Transport' },
  { value: 'q', label: 'Education' },
  { value: 'w', label: 'Emergency Room/Trauma' },
  { value: 'e', label: 'Family Practice' },
  { value: 'r', label: 'Geriatrics/Gerontology' },
  { value: 't', label: 'Home Care' },
  { value: 'y', label: 'Infection Control' },
  { value: 'u', label: 'Management' },
  { value: 'i', label: 'Maternity (Antepartum & Postpartum)' },
  { value: 'o', label: 'Maternity (Labour & Delivery)' },
  { value: 'p', label: 'Medicine/Surgery' },
  { value: 'l', label: 'Midwifery' },
  { value: 'k', label: 'Neonatal Intensive Care' },
  { value: 'h', label: 'Neurology' },
  { value: 'g', label: 'New Graduate' },
  { value: 'f', label: 'Nurse Executive' },
  { value: 'd', label: 'Occupational Health' },
  { value: 's', label: 'Oncology' },
  { value: 'a', label: 'Operating Room (Adult)' },
  { value: 'z', label: 'Operating Room (Pediatric)' },
  { value: 'x', label: 'Outreach' },
  { value: 'c', label: 'Palliative Care' },
  { value: 'v', label: 'Pediatrics' },
  { value: 'b', label: 'Post Anesthetic Recovery' },
  { value: 'n', label: 'Primary Care Clinic' },
  { value: 'm', label: 'Psychiatry/Mental Health' },
  { value: 'qw', label: 'Public Health' },
  { value: 'as', label: 'Rehabilitation' },
  { value: 'sd', label: 'Rehabilitation/Spinal Unit' },
  { value: 'fd', label: 'Renal Dialysis' },
  { value: 'gf', label: 'Research' },
  { value: 'hg', label: 'Still in School' },
  { value: 'gsh', label: 'Transitional Care Nurse' },
  { value: 'jhs', label: 'Wound Care' },
];

export const recruitmentStatusArray = [
  { value: 'In Licensing Process', label: 'In Licensing Process' },
  { value: 'In Hiring Process', label: 'In Hiring Process' },
  { value: 'In Relocation Process', label: 'In Relocation Process' },
];

export const countriesArray = [
  { value: '1', label: 'Canada' },
  { value: '2', label: 'United States' },
  { value: '3', label: 'United Kingdom' },
  { value: '4', label: 'Ireland' },
  { value: '5', label: 'Australia' },
  { value: '6', label: 'Phillipines ' },
  { value: '7', label: 'India' },
  { value: '8', label: 'Nigeria' },
  { value: '9', label: 'Jamaica' },
  { value: '10', label: 'Kenya' },
  { value: '11', label: 'Other' },
];

export const nursingEducationArray = [
  { value: 'diploma-certificate', label: 'Diploma/Certificate of Nursing' },
  { value: 'associate-degree', label: 'Associate Degree of Nursing' },
  { value: 'bachelor', label: 'Bachelor of Nursing or Bachelor of Science in Nursing' },
  { value: 'master-nursing', label: 'Master of Nursing' },
  { value: 'master-nursing-pract', label: 'Master of Nursing - Nurse Practitioner' },
  { value: 'phd', label: 'Phd' },
  { value: 'diploma-degree', label: 'Combined Diploma/Degree in Midwifery & Nursing' },
  { value: 'other', label: 'Other' },
];
