export enum STATUS {
  INTAKE = 'INTAKE',
  COMPLETED_SLA = 'Completed Simulation Lab Assessment (SLA)',
  APPLIED_TO_BCCNM = 'Applied to BCCNM',
  SENT_FIRST_STEPS_DOCUMENT = 'Sent First Steps document to candidate',
  RECEIVED_NNAS_REPORT = 'Received NNAS Report',
  APPLIED_TO_NNAS = 'Applied to NNAS',
  RECEIVED_WORK_PERMIT = 'Received Work Permit (Arrival in Canada)',
  COMPLETED_CBA = 'Completed Computer-Based Assessment (CBA)',
  RECEIVED_PR = 'Received Permanent Residency',
  BCCNM_PROVISIONAL_LICENSE_LPN = 'BCCNM Provisional Licence LPN',
  BCCNM_PROVISIONAL_LICENSE_RN = 'BCCNM Provisional Licence RN',
  REX_PN_WRITTEN = 'REx-PN - Written',
  REX_PN_PASSED = 'REx-PN - Passed',
  BCCNM_FULL_LICENCE_LPN = 'BCCNM Full Licence LPN',
  REGISTERED_AS_AN_HCA = 'Registered as an HCA',
  REGISTRATION_JOURNEY_COMPLETED = 'Registration Journey Complete',
  REFERRED_TO_FNHA = 'Applicant Referred to FNHA',
  REFERRED_TO_FHA = 'Applicant Referred to FHA',
  REFERRED_TO_IHA = 'Applicant Referred to IHA',
  REFERRED_TO_NHA = 'Applicant Referred to NHA',
  REFERRED_TO_PHC = 'Applicant Referred to PHC',
  REFERRED_TO_PHSA = 'Applicant Referred to PHSA',
  REFERRED_TO_VCHA = 'Applicant Referred to VCHA',
  REFERRED_TO_VIHA = 'Applicant Referred to VIHA',
  PRESCREEN_PASSED = 'Candidate Passed Pre-Screen',
  PRESCREEN_NOT_PASSED = 'Candidate Did Not Pass Pre-Screen',
  INTERVIEW_PASSED = 'Candidate Passed Interview',
  INTERVIEW_NOT_PASSED = 'Candidate Did Not Pass Interview',
  REFERENCE_CHECK_PASSED = 'Candidate Passed Reference Check',
  REFERENCE_CHECK_NOT_PASSED = 'Candidate Did Not Pass Reference Check',
  JOB_OFFER_ACCEPTED = 'Job Offer Accepted',
  JOB_OFFER_NOT_ACCEPTED = 'Job Offer Not Accepted',
  JOB_COMPETITION_CANCELLED = 'Job Competition Cancelled',
  HA_NOT_INTERESTED = 'HA is Not Interested',
  NO_POSITION_AVAILABLE = 'No Position Available',
  SUBMITTED_BC_PNP_APPLICATION = 'Submitted application to BC PNP',
  READY_FOR_JOB_SEARCH = 'Applicant Ready for Job Search',
  REFERRED_TO_NCAS = 'Referred to NCAS',
  REFERRAL_ACKNOWLEDGED = 'Referral Acknowledged/Reviewed',
  COMPLETED_NCAS = 'Completed NCAS',
  COMPLETED_LANGUAGE_REQUIREMENT = 'Completed English Language Requirement',
  SENT_SECOND_STEPS_DOCUMENT = 'Sent Second Steps document to candidate',
  BCCNM_FULL_LICENSE_RN = 'BCCNM Full Licence RN',
  REFERRED_TO_REGISTRATION_EXAM = 'Referred to Registration Exam',
  NCLEX_PASSED = 'NCLEX – Passed',
  WORK_PERMIT_APPROVAL_RECEIVED = 'Received Work Permit Approval Letter',
  REFERRED_TO_ADDITIONAL_EDUCTION = 'Referred to Additional Education',
  NCLEX_WRITTEN = 'NCLEX – Written',
  COMPLETED_ADDITIONAL_EDUCATION = 'Completed Additional Education',
  RECEIVED_CONFIRMATION_OF_NOMINATION = 'Received Confirmation of Nomination',
  SUBMITTED_DOCUMENTS = 'Submitted Documents (NNAS Application in Review)',
  WITHDREW_FROM_PROGRAM = 'Withdrew from IEN program',
  SUBMITTED_WORK_PERMIT_APPLICATION = 'Submitted Work Permit Application',
  SENT_EMPLOYER_DOCUMENTS_TO_HMBC = 'Sent employer documents to HMBC',
  WITHDREW_FROM_COMPETITION = 'Candidate Withdrew from Competition',
}

export const COMPLETED_STATUSES = [
  STATUS.PRESCREEN_NOT_PASSED,
  STATUS.INTERVIEW_NOT_PASSED,
  STATUS.REFERENCE_CHECK_NOT_PASSED,
  STATUS.WITHDREW_FROM_PROGRAM,
  STATUS.WITHDREW_FROM_COMPETITION,
  STATUS.HA_NOT_INTERESTED,
  STATUS.NO_POSITION_AVAILABLE,
  STATUS.JOB_COMPETITION_CANCELLED,
  STATUS.JOB_OFFER_ACCEPTED,
  STATUS.JOB_OFFER_NOT_ACCEPTED,
];
