export enum STATUS {
  'Registered_for_HMBC_services_' = 1,
  'Profile_Complete',
  'Applied_to_NNAS',
  'Documents_Submitted',
  'Received_NNAS_Report',
  'HMBC_Registered_for_HMBC_services' = 101,
  'HMBC_Profile_Complete',
  'Candidate_Applied_to_NNAS' = 201,
  'Candidate_Documents_Submitted',
  'Candidate_Received_NNAS_Report',
  'Candidate_Applied_to_BCCNM',
  'Candidate_Completed_English_Language_Requirement',
  'Candidate_Referred_to_NCAS',
  'Candidate_Completed_CBA',
  'Candidate_Completed_OA_SLA',
  'Candidate_Completed_NCAS',
  'Candidate_Referred_to_Additional_Education',
  'Candidate_Completed_Additional_Education',
  'Candidate_Referred_to_NCLEX',
  'Candidate_Eligible_for_Provisional_Licensure',
  'Candidate_NCLEX_Written',
  'Candidate_NCLEX_Passed_',
  'Candidate_BCCNM_Licensed_Full_License',
  'Prescreen_completed' = 301,
  'Interview_completed',
  'References_completed',
  'Offered_position',
  'Candidate_withdrew',
  'Candidate_was_unresponsive',
  'Candidate_was_not_selected',
  'Candidate_accepted_the_job_offer',
  'HMBC_First_Steps_Document_Sent' = 401,
  'HA_Documents_sent_to_HMBC',
  'Candidate_Application_Submitted_to_BC_PNP',
  'Candidate_Confirmation_of_Nomination_Received',
  'HMBC_Second_Steps_Sent',
  'Candidate_Work_Permit_Application_Submitted_',
  'Candidate_Work_Permit_Approval_Letter_Received_',
  'Candidate_Arrival_in_Canada_Work_Permit_Received',
  'Candidate_Permanent_Residency',
  'HA_Candidate_started_job',
  'IEN_HMBC_Process' = 10001,
  'IEN_Licensing_Registration',
  'IEN_Recruitment',
  'BC_PNP',
  'Final_Milestone',
}

export const COMPLETED_STATUSES = [
  STATUS.Candidate_withdrew,
  STATUS.Candidate_was_unresponsive,
  STATUS.Candidate_was_not_selected,
  STATUS.Candidate_accepted_the_job_offer,
];
