name: ZAP Scan
on:
  push:
    branches:
      - main
    tags:
      - security

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: ci-${github.ref}-sec
    environment:
      name: dev

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: https://d309kopm8ags5f.cloudfront.net
          cmd_options: '-I'
          rules_file_name: '.zap/rules.tsv'
