name: PROD - Deploy Apps
on:
  push:
    tags:
      - prod
env:
  TF_VERSION: 1.1.1
  ENV_NAME: prod

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: ci-${{ github.ref }}-prod
    env:
      CLOUDFRONT_ID: '${{ secrets.CLOUDFRONT_ID }}'
      AWS_ACCOUNT_ID: '${{ secrets.AWS_ACCOUNT_ID}}'
    environment:
      name: prod
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/cache@v4
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{secrets.AWS_SA_ROLE_ARN}}
          aws-region: ca-central-1

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform apply
        run: make apply

      - name: Install dependencies
        run: yarn

      - name: Clean Build Folder
        run: make pre-build

      - name: Build web app
        run: make build-web

      - name: Build api
        run: make build-api

      - name: Deploy All
        run: make deploy-all
