name: Deployment to aws test environment
on:
  push:
    tags:
      - test
env:
  PROJECT: ehpr
  ENV_NAME: test
  TF_VERSION: 1.1.1
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: ci-${github.ref}-test
    environment:
      name: test
    env:
      CLOUDFRONT_ID: '${{ secrets.CLOUDFRONT_ID }}'
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/cache@v2
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: Print Environment
        run: make print-env

      - name: Setup terraform dir
        run: make pre-build

      - name: Build web app
        run: make build-web

      - name: Build api
        run: make build-api

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ca-central-1
          role-to-assume: ${{ secrets.AWS_SA_ROLE_ARN }}
          role-duration-seconds: 900
          role-session-name: ci-deployment

      - name: Terraform config
        run: |
          make plan
          make deploy-infra
          make deploy-app
