name: Web PR Checks
on:
  pull_request:
    paths:
      - 'apps/web/**'
      - 'packages/common/**'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/cache@v2
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn workspace @ien/web install

      - name: Run formatting check
        run: yarn format:check

      - name: Build dependencies
        run: yarn build-common

      - name: Lint web package
        run: yarn workspace @ien/web lint

      - name: Unit-test web package
        run: yarn workspace @ien/web test

      - name: Test web package cypress
        uses: cypress-io/github-action@v2
        with:
          start: make run-test-backend
          working-directory: ./
          project: ./apps/web
          wait-on: 'http://localhost:3000'
        env:
          E2E_TEST_USERNAME: '${{ secrets.E2E_TEST_USERNAME}}'
          E2E_TEST_PASSWORD: '${{ secrets.E2E_TEST_PASSWORD}}'
          AUTH_REALM: 'moh_applications'

      - name: Build web package
        run: yarn workspace @ien/web build
