name: API PR Checks
on:
  pull_request:
    paths:
      - 'apps/api/**'
      - 'apps/web/**'
      - 'packages/common/**'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - uses: actions/cache@v3
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn workspace @ien/api install

      - name: Run formatting check
        run: yarn format:check

      - name: Build dependencies
        run: yarn build-common

      - name: Lint API Package
        run: yarn workspace @ien/api lint

      - name: Unit test API Package
        run: yarn workspace @ien/api test

      - name: Integration test API Package
        run: make api-integration-test
