name: Common PR Checks
on:
  pull_request:
    paths:
      - 'packages/common/**'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/cache@v4
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn workspace @ien/common install

      - name: Run formatting check
        run: yarn format:check

      - name: Lint web package
        run: yarn workspace @ien/common lint

      - name: Test web package
        run: yarn workspace @ien/common test

      - name: Build web package
        run: yarn workspace @ien/common build
