name: Web PR Checks
on:
  pull_request:
    paths:
      - 'apps/api/**'
      - 'apps/web/**'
      - 'packages/common/**'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - uses: actions/cache@v3
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn workspace @ien/web install

      - name: Run formatting check
        run: yarn format:check

      - name: Build dependencies
        run: yarn build-common

      - name: Lint web package
        run: yarn workspace @ien/web lint

      - name: Unit-test web package
        run: yarn workspace @ien/web test
