name: PR Cypress e2e Checks
on:
  pull_request:
    paths:
      - 'apps/api/**'
      - 'apps/web/**'
      - 'packages/common/**'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Install dependencies
        run: yarn install

      - name: Run application and Cypress e2e tests
        run: make test-e2e
        env:
          CYPRESS_RECORD_KEY: '${{ secrets.CYPRESS_RECORD_KEY }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ENV_NAME: 'local'
          E2E_TEST_USERNAME: '${{ secrets.E2E_TEST_USERNAME}}'
          E2E_TEST_PASSWORD: '${{ secrets.E2E_TEST_PASSWORD}}'
          AUTH_URL: 'https://keycloak.freshworks.club/auth'
          AUTH_REALM: 'ien'
          AUTH_CLIENTID: 'IEN'
          NEXT_PUBLIC_API_URL: 'http://localhost:4000/api/v1'
          NEXT_PUBLIC_AUTH_REALM: 'ien'
          NEXT_PUBLIC_AUTH_CLIENTID: 'IEN'
          NEXT_PUBLIC_AUTH_URL: 'https://keycloak.freshworks.club/auth'
