name: Web Accessibility PR Checks
on:
  pull_request:
    paths:
      - 'apps/web/**'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/cache@v2
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Build dependencies
        run: yarn build-common

      - name: Start web app
        run: NEXT_PUBLIC_PREFILLED_FORM=true yarn workspace @ehpr/web dev &

      - name: sleep until webapp is up
        run: |
          until $(curl --output /dev/null --silent --fail http://localhost:3000); do
              echo '.'
              ((c++)) && ((c==10)) && c=0 && break # don't run more than 10 times
              sleep 5
          done

      - name: Accessibility Test web package
        run: make accessibility-test

      - name: generate markdown from test results
        run: make generate-accessibility-results
        if: ${{ failure() }}

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('./packages/accessibility/out/accessibility_results.md', 'utf8');
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
        if: ${{ failure() }}
