name: Terraform PR Checks
on:
  pull_request:
    paths:
      - 'terraform/**'

env:
  TF_VERSION: 1.1.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: ci-${{ github.ref }}-tf
    env:
      CLOUDFRONT_ID: '${{ secrets.CLOUDFRONT_ID }}'
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: Terraform Init
        run: make init

      - name: Terraform Plan
        id: plan
        run: make plan
        continue-on-error: true

      # From:
      # https://github.com/hashicorp/setup-terraform#usage

      - name: Show Plan on PR
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
